name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v5

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 依存関係をインストール
        run: npm install --no-audit --no-fund

      - name: Unit Testを実行
        run: npm test

      - name: アプリケーションをBuild
        run: npm run build
